---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eviction-guard-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eviction-guard.io
  resources:
  - evictionguardpolicies
  - proactivewindows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eviction-guard.io
  resources:
  - evictionguardpolicies/finalizers
  - proactivewindows/finalizers
  verbs:
  - update
- apiGroups:
  - eviction-guard.io
  resources:
  - evictionguardpolicies/status
  - proactivewindows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
