apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eviction-guard.fullname" . }}
  labels:
    {{- include "eviction-guard.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eviction-guard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "eviction-guard.labels" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      serviceAccountName: {{ include "eviction-guard.fullname" . }}
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect={{ .Values.leaderElect }}
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8080
            {{- if .Values.webhook.enabled }}
            - --webhook-cert-dir=/tmp/k8s-webhook-server/serving-certs
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
            {{- if .Values.webhook.enabled }}
            - name: webhook
              containerPort: 9443
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.webhook.enabled }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          {{- end }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "eviction-guard.webhookSecretName" . }}
      {{- end }}
