{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eviction-guard.fullname" . }}
  labels:
    {{- include "eviction-guard.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eviction-guard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      control-plane: controller-manager
{{- end }}
