//go:build !ignore_autogenerated

/*
Copyright 2026 Vikas Verma.

Licensed under the MIT License.
See LICENSE in the project root for license information.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendCatalogEntry) DeepCopyInto(out *BackendCatalogEntry) {
	*out = *in
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]BackendPatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendCatalogEntry.
func (in *BackendCatalogEntry) DeepCopy() *BackendCatalogEntry {
	if in == nil {
		return nil
	}
	out := new(BackendCatalogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendPatch) DeepCopyInto(out *BackendPatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendPatch.
func (in *BackendPatch) DeepCopy() *BackendPatch {
	if in == nil {
		return nil
	}
	out := new(BackendPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomDisruptionSignal) DeepCopyInto(out *CustomDisruptionSignal) {
	*out = *in
	if in.Taint != nil {
		in, out := &in.Taint, &out.Taint
		*out = new(TaintMatch)
		**out = **in
	}
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(KeyValueMatch)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(KeyValueMatch)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomDisruptionSignal.
func (in *CustomDisruptionSignal) DeepCopy() *CustomDisruptionSignal {
	if in == nil {
		return nil
	}
	out := new(CustomDisruptionSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionGuardPolicy) DeepCopyInto(out *EvictionGuardPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionGuardPolicy.
func (in *EvictionGuardPolicy) DeepCopy() *EvictionGuardPolicy {
	if in == nil {
		return nil
	}
	out := new(EvictionGuardPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvictionGuardPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionGuardPolicyList) DeepCopyInto(out *EvictionGuardPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvictionGuardPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionGuardPolicyList.
func (in *EvictionGuardPolicyList) DeepCopy() *EvictionGuardPolicyList {
	if in == nil {
		return nil
	}
	out := new(EvictionGuardPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvictionGuardPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionGuardPolicySpec) DeepCopyInto(out *EvictionGuardPolicySpec) {
	*out = *in
	in.NodeFilter.DeepCopyInto(&out.NodeFilter)
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SpareReplicas != nil {
		in, out := &in.SpareReplicas, &out.SpareReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxBuffer != nil {
		in, out := &in.MaxBuffer, &out.MaxBuffer
		*out = new(int32)
		**out = **in
	}
	if in.MaxConcurrentWindows != nil {
		in, out := &in.MaxConcurrentWindows, &out.MaxConcurrentWindows
		*out = new(int32)
		**out = **in
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make(map[string]BackendCatalogEntry, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ScaleBackAfter != nil {
		in, out := &in.ScaleBackAfter, &out.ScaleBackAfter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxWindow != nil {
		in, out := &in.MaxWindow, &out.MaxWindow
		*out = new(v1.Duration)
		**out = **in
	}
	out.Stamp = in.Stamp
	if in.DisruptionSignals != nil {
		in, out := &in.DisruptionSignals, &out.DisruptionSignals
		*out = make([]DisruptionSignal, len(*in))
		copy(*out, *in)
	}
	if in.CustomSignals != nil {
		in, out := &in.CustomSignals, &out.CustomSignals
		*out = make([]CustomDisruptionSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionGuardPolicySpec.
func (in *EvictionGuardPolicySpec) DeepCopy() *EvictionGuardPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EvictionGuardPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionGuardPolicyStatus) DeepCopyInto(out *EvictionGuardPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionGuardPolicyStatus.
func (in *EvictionGuardPolicyStatus) DeepCopy() *EvictionGuardPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(EvictionGuardPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionGuardWindow) DeepCopyInto(out *EvictionGuardWindow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionGuardWindow.
func (in *EvictionGuardWindow) DeepCopy() *EvictionGuardWindow {
	if in == nil {
		return nil
	}
	out := new(EvictionGuardWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvictionGuardWindow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionGuardWindowList) DeepCopyInto(out *EvictionGuardWindowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvictionGuardWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionGuardWindowList.
func (in *EvictionGuardWindowList) DeepCopy() *EvictionGuardWindowList {
	if in == nil {
		return nil
	}
	out := new(EvictionGuardWindowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvictionGuardWindowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionGuardWindowSpec) DeepCopyInto(out *EvictionGuardWindowSpec) {
	*out = *in
	out.Target = in.Target
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]ScaleAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VulnerableNodes != nil {
		in, out := &in.VulnerableNodes, &out.VulnerableNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WindowUntil != nil {
		in, out := &in.WindowUntil, &out.WindowUntil
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionGuardWindowSpec.
func (in *EvictionGuardWindowSpec) DeepCopy() *EvictionGuardWindowSpec {
	if in == nil {
		return nil
	}
	out := new(EvictionGuardWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionGuardWindowStatus) DeepCopyInto(out *EvictionGuardWindowStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionGuardWindowStatus.
func (in *EvictionGuardWindowStatus) DeepCopy() *EvictionGuardWindowStatus {
	if in == nil {
		return nil
	}
	out := new(EvictionGuardWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyValueMatch) DeepCopyInto(out *KeyValueMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValueMatch.
func (in *KeyValueMatch) DeepCopy() *KeyValueMatch {
	if in == nil {
		return nil
	}
	out := new(KeyValueMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeFilter) DeepCopyInto(out *NodeFilter) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludeLabelSelector != nil {
		in, out := &in.ExcludeLabelSelector, &out.ExcludeLabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InstanceTypes != nil {
		in, out := &in.InstanceTypes, &out.InstanceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CapacityTypes != nil {
		in, out := &in.CapacityTypes, &out.CapacityTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TaintSelector != nil {
		in, out := &in.TaintSelector, &out.TaintSelector
		*out = make([]TaintMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeFilter.
func (in *NodeFilter) DeepCopy() *NodeFilter {
	if in == nil {
		return nil
	}
	out := new(NodeFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleAction) DeepCopyInto(out *ScaleAction) {
	*out = *in
	if in.StampKeys != nil {
		in, out := &in.StampKeys, &out.StampKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleAction.
func (in *ScaleAction) DeepCopy() *ScaleAction {
	if in == nil {
		return nil
	}
	out := new(ScaleAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StampSpec) DeepCopyInto(out *StampSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StampSpec.
func (in *StampSpec) DeepCopy() *StampSpec {
	if in == nil {
		return nil
	}
	out := new(StampSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaintMatch) DeepCopyInto(out *TaintMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaintMatch.
func (in *TaintMatch) DeepCopy() *TaintMatch {
	if in == nil {
		return nil
	}
	out := new(TaintMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
